package com.xiangmu.pojo;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class Liuyanban implements java.io.Serializable
{

	private int id;
	private int user_id;
	private String neirong;
	private String liuyanshi;
	
	private String huifu;
	private String huifushi;
	
	private User user;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUser_id() {
		return user_id;
	}

	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}

	public String getNeirong() {
		return neirong;
	}

	public void setNeirong(String neirong) {
		this.neirong = neirong;
	}

	public String getLiuyanshi() {
		return liuyanshi;
	}

	public void setLiuyanshi(String liuyanshi) {
		this.liuyanshi = liuyanshi;
	}

	public String getHuifu() {
		return huifu;
	}

	public void setHuifu(String huifu) {
		this.huifu = huifu;
	}

	public String getHuifushi() {
		return huifushi;
	}

	public void setHuifushi(String huifushi) {
		this.huifushi = huifushi;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Liuyanban [id=" + id + ", user_id=" + user_id + ", neirong=" + neirong + ", liuyanshi=" + liuyanshi
				+ ", huifu=" + huifu + ", huifushi=" + huifushi + ", user=" + user + "]";
	}
	
}